FROM grafana/grafana:latest

COPY provisioning/datasources/loki.yaml /etc/grafana/provisioning/datasources/loki.yaml
COPY provisioning/datasources/postgres.yaml /etc/grafana/provisioning/datasources/postgres.yaml
